name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # The Go version to download (if necessary) and use.

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make all

      - name: Unit-test
        run: make unit-test

      - name: Integration-test
        run: make integration-test